# SPDX-License-Identifier: GPL-2.0-only

CONFIG_QCOM_HGSL = m
CONFIG_QCOM_HGSL_TCSR_SIGNAL = y

KDIR := $(TOP)/kernel_platform/common

ifeq ($(HGSL_PATH),)
HGSL_PATH=$(src)
endif

include $(HGSL_PATH)/config/hgsl.conf

HGSL_GIT_HASH := $(shell git -C $(HGSL_PATH) rev-parse --short=7 HEAD 2>/dev/null || echo unknown)

filechk_hgsl_git_version.h = { \
	echo '/* SPDX-License-Identifier: GPL-2.0-only */'; \
	echo '/* This file is generated by Kbuild. Do not edit. */'; \
	echo '$(pound)ifndef __HGSL_GIT_VERSION_H'; \
	echo '$(pound)define __HGSL_GIT_VERSION_H'; \
	echo; \
	echo '$(pound)define HGSL_GIT_HASH "$(HGSL_GIT_HASH)"'; \
	echo; \
	echo '$(pound)endif /* __HGSL_GIT_VERSION_H */'; \
}

$(obj)/hgsl_git_version.h: FORCE
	$(call filechk,hgsl_git_version.h)

ccflags-y += -I$(obj)

ccflags-y += -I$(HGSL_PATH)  \
            -I$(HGSL_PATH)/include \
            -I$(HGSL_PATH)/include/linux \
            -Wno-unused-function \
            -Wno-unused-parameter \
            -Wno-unused-variable

obj-$(CONFIG_QCOM_HGSL) += qcom_hgsl.o

qcom_hgsl-y = hgsl.o \
            hgsl_gmugos.o \
            hgsl_hyp.o \
            hgsl_hyp_socket.o \
            hgsl_memory.o \
            hgsl_sync.o \
            hgsl_events.o \
            hgsl_drawobj.o \
            hgsl_dispatch.o \
            hgsl_mmu.o \
            hgsl_iommu.o \
            hgsl_snapshot.o \
            hgsl_pm4_dec_4_7.o

qcom_hgsl-$(CONFIG_QCOM_HGSL_TCSR_SIGNAL) += hgsl_tcsr.o
qcom_hgsl-$(CONFIG_SYSFS) += hgsl_sysfs.o
qcom_hgsl-$(CONFIG_DEBUG_FS) += hgsl_debugfs.o

$(addprefix $(obj)/, $(qcom_hgsl-y) $(qcom_hgsl-$(CONFIG_QCOM_HGSL_TCSR_SIGNAL)) $(qcom_hgsl-$(CONFIG_SYSFS)) $(qcom_hgsl-$(CONFIG_DEBUG_FS))): $(obj)/hgsl_git_version.h
